### ISSUE TITLE
Möglichkeit, IDs oder Klassen als Trigger zu definieren

### ISSUE THREAD

**Issue by cukabeka** [RexDude/ckeditor#20]
Da ich in manchen Addons, zB XForm, den CKeditor nutzen möchte, wäre toll, wenn man im Backend alternativ auch Klassen oder IDs angeben kann, auf denen der Editor getriggert wird. So muss ich nicht im Addon-Code herumpfuschen, um die CKE-Klasse hinzuzufügen, und bei einem Update des Addons ist meine Anpassung für CKE nicht wieder weg.. 

Ich denke da zb an die ID #rex_xform_email_template_Template_body_html

**Comment by alexplusde** [comment]
Sorry, ich hab gerade ein eigenes Issue deswegen aufgemacht mit genau dem Wunsch.

**Comment by RexDude** [comment]
Der CKEditor lässt sich über die Klasse "ckeditor" erzeugen normalerweise auch in Xform.

**Comment by alexplusde** [comment]
Ach... so? :D

Dann habe ich in den letzten 20 Minuten einfach mehr über den Aufbau von Addons in Redaxo 4.6 gelernt (und wollte es gerade selbst versuchen). Umso besser! 

Ich hab's in deiner Readme hier und in der Addon-Hilfe echt nirgends entdeckt.

**Comment by RexDude** [comment]
Da stehst doch? ;)

https://github.com/RexDude/ckeditor/blob/master/README.md#ckeditor-in-addons-wie-xform-metainfos-etc-einsetzen

**Comment by alexplusde** [comment]
Komplett überlesen. Heute ist nicht mein Tag. Danke, Rudi.
