### ISSUE TITLE
CKEditor geht nicht im Medienpool per .ckeditor Klasse

### ISSUE THREAD

**Issue by RexDude** [RexDude/ckeditor#22]

**Comment by skerbis** [comment]
Habe ich auch gerade festgestellt. Währe toll, wenn Du das kurzfristig lösen könntest, da der TinyMCE so veraltet ist, dass er nicht zu gebrauchen ist.

**Comment by RexDude** [comment]
Ich habe bereits mehrmals geschaut war aber noch nicht wiklich erfolgreich.
Vielleicht findest du oder jemand anderes eine Lösung.
