### ISSUE TITLE
Bug(?): (manche) Custom Styles werden ignoriert

### ISSUE THREAD

**Issue by JeGr** [RexDude/ckeditor#24]
Laut Dokumentation vorgegangen um weitere Styles hinzuzufügen:

    CKEDITOR.stylesSet.add('default', [
        { name: 'Grün', element: 'span', attributes: { 'class': 'green' } },
        { name: 'Blau', element: 'span', attributes: { 'class': 'blue' } }
        // no comma after last entry!!!
    ]);

In meinem Falle:

    CKEDITOR.stylesSet.add('default', [
        { name: 'Box Info', element: 'p', attributes: { 'class': 'msg info' } },
        { name: 'Box Warnung', element: 'p', attributes: { 'class': 'msg notice' } },
        { name: 'Box Erfolg', element: 'p', attributes: { 'class': 'msg success' } },
        { name: 'Box Fehler', element: 'p', attributes: { 'class': 'msg error' } },
        { name: 'Tabelle alternativ', element: 'table', attributes: { 'class': 'alt' } }
        // no comma after last entry!!!
    ]);

Kurioserweise habe ich im Editor nun aber nur die Auswahl zwischen "Box Warnung" und "Box Erfolg". Info und Fehler werden schlichtweg ignoriert. Klicke ich in eine Tabelle wird zusätzlich zu Warnung und Erfolg auch die alternative Tabelle angezeigt (fein). Irgendwie wird aber Info und Fehler weggeschluckt. Mehr als die zwei Blockelemente mag er nicht anzeigen.

Grüße

**Comment by RexDude** [comment]
Kannst du das bitte ins Forum schreiben? Das ist weder ein Bug noch ein Feature des Addons. Und poste dann bitte deine komplette Moduleingabe dazu.

**Comment by JeGr** [comment]
In welches Forum genau? :) Aber sonst gerne, ich nehme an, dass ich nicht der einzige bin?

**Comment by RexDude** [comment]
Yup :) Kannst natürlich auch ins ckeditor.com forum schreiben.

ja es ist ckeditor spezifisch und hat mit dem addon nix zu tun. und deshalb forum weil da noch viel mehr leute mitlesen und andere auch mitsupporten können.

**Comment by JeGr** [comment]
OK kommt gleich :)
