### ISSUE TITLE
Konflikt mit Redactor

### ISSUE THREAD

**Issue by skerbis** [RexDude/ckeditor#27]
Ich habe in einem yform-Feld  {"class":"redactorEditor2-simple"} für den redactor-Editor festgelegt. 
Dieser wird auch angezeigt. 
Klicke ich jedoch in das Textfeld, wird fixiert der CKeditor über den redactor gelegt, mit all seinen Funktionen. 

Vor Click, 
<img width="667" alt="bildschirmfoto 2017-02-19 um 18 18 01" src="https://cloud.githubusercontent.com/assets/791247/23104526/ec4b66a8-f6cf-11e6-8080-2a667400c354.png">

nach Click:
<img width="681" alt="bildschirmfoto 2017-02-19 um 18 18 11" src="https://cloud.githubusercontent.com/assets/791247/23104528/f07f6a9e-f6cf-11e6-912f-ac919b649fda.png">

**Comment by RexDude** [comment]
lustig :) keine ahnung was da los ist. normal initialisiert der ck sich nur auf die class=ckeditor
und wieso brauchst du eigentlich 2 editoren?

**Comment by skerbis** [comment]
ist mir nur aufgefallen, da ich schauen wollte wo ich überall redactor im Einsatz habe.

**Comment by RexDude** [comment]
Willst du hier noch was machen @skerbis. Sonst close.

**Comment by skerbis** [comment]
@RexDude es war ein Hinweis an Dich. Ich habe es nicht weiter untersucht.

**Comment by RexDude** [comment]
Thx.
