### ISSUE TITLE
Bild aus Medienpool einfügen

### ISSUE THREAD

**Issue by georgkaser** [RexDude/ckeditor#30]
Yeah, er ist wieder da! Du hast ja keine Ahnung wie lange ich auf eine Portierung des ckeditor warte :) Danke dafür!!

Du, wie krieg ich denn das hin, dass der Medienpool aufgeht, wenn ich `['Image']` zum Profil hinzufüg?

Edit: Ah, shit - habs grad gelesen: "Der Mediabutton für das CKEditor Image Plugin wird aktuell nicht unterstützt. Image sollte daher aus der Toolbar entfernt werden." (wer lesen kann ist besser dran ;))

Das bräucht ich dringend...

**Comment by RexDude** [comment]
Ähh sorry? ...und freut mich das dir der port zusagt :))

Hmm ich schau mal heut oder morgen nach ner schnellen Lösung. Hab so leider gar keine Zeit für sowas sonst. Aber wie in der Readme steht. Mach dir doch ein text + bild modul mit nem REX_MEDIABUTTON[]...

**Comment by fietstouring** [comment]
ich würd mal mit dem Inspector reinschauen, kann mich erinnern dass das in der 4er einfach wegen einem display:none nicht angezeigt wurde.

**Comment by RexDude** [comment]
In dem Fall ist es nicht die Ursache.

**Comment by georgkaser** [comment]
Ja, Text und Bildmodul geht in dem Fall nicht. Ich möchte ein Richtextfeld in einer yForm Tabelle verwenden (Blog) und da zwischen den Absätzen beliebig Bilder einfügen können.

**Comment by fietstouring** [comment]
inline Bilder mit Textumfluss geht ja sonst auch nicht

**Comment by georgkaser** [comment]
Freilich geht das:

<img width="773" alt="bildschirmfoto 2017-02-20 um 16 36 20" src="https://cloud.githubusercontent.com/assets/6472869/23131572/caf3a2c0-f78a-11e6-9926-491077631ee0.png">

**Comment by RexDude** [comment]
@webghostx to the rescue...?!

**Comment by fietstouring** [comment]
@georgkaser na ja ich meinte ja ohne die Image-Funktion im ck gehts nicht...

**Comment by RexDude** [comment]
@fietstouring mit 2 artikel blöcken evtl.

**Comment by georgkaser** [comment]
Wie machst du Blöcke in yForm? Ich hab zwei Textfelder: short_text und long_text (short_text ist für den Teaser). Meinst du mehrere Textfelder um den Artikel dann aufzusplitten?

**Comment by RexDude** [comment]
Ja ich meinte Artikel. yForm geht so nicht.

**Comment by fietstouring** [comment]
@RexDude gib doch mal nen Hinweis, wo man da reingucken muss, wo haperts denn? Anbindung an den Medienpool? 

Für Text-um-Bild verwende ich das schon sehr gern. Alles andere dürfte mühsam sein (mehrere Blöcke)

**Comment by RexDude** [comment]
Nagut also...

In der 4er Version wurde ein zusätzliches Image2 Plugin eingebunden. Dieses wurde über diesen Code mit dem Medienpool Button ausgestattet: https://github.com/RexDude/ckeditor/blob/master/assets/redaxo.js#L27-L45 Eine Möglichkeit wäre also das Teil mitzuliefern so wie gehabt. Ohne dass dieses Feature implementiert ist würd ich aber davon abraten weil bei nem Update das Plugin verloren geht: https://github.com/RexDude/ckeditor/issues/31

Mein gewünschter neuer Weg wäre dass breits mitgelieferte Image Plugin zu nutzen da es auch mehr Features enthält und im Full Package auto. mit dabei ist. Wie man den Mediepool Button einfügt weiss ich noch nicht. Evtl. gehts sehr einfach wie bei Image2 oder komplizierter wie beim Linkdialog (siehe darunter den Code).  Hier noch ein paar Links zu dem Thema, evtl. hilft auch Google weiter.

http://docs.ckeditor.com/#!/guide/dev_file_browse_upload

http://docs.ckeditor.com/#!/guide/dev_dialog_add_file_browser

http://docs.ckeditor.com/#!/guide/dev_file_browser_api

**Comment by RexDude** [comment]
Könnte dass einer testen obs so passt?

**Comment by georgkaser** [comment]
Funktioniert super! Habs grad getestet, danke dir dafür. Wie ist das eigentlich mit dem Mediamanager, kann man die URL irgendwie abändern, dass man das Bild auch verkleinern kann? Die Leute betten sonst schnell Bilder ein, die eher nicht webtauglich sind.

**Comment by RexDude** [comment]
Ok cool :)
Ja da kann man sicherlich was einbauen  Aber ich werd mich jetzt lieber noch um andere Dinge und Addons kümmern. Kannst ja ein neues Issue anlegen. 

Ach und hier noch ein Workaround: Den Outpt hernehmen, per regex die href's der img's umschreiben so dass das über den media manager läuft.

Hab noch ne Frage: sollte man nicht besser Horizontal-Abstand, Vertikal-Abstand und Rahmen ganz entfernen? Da soll doch sicher kein Redaltuer was machen und der Programmier macht das eh über CSS.

**Comment by RexDude** [comment]
> Ach und hier noch ein Workaround: Den Outpt hernehmen, per regex die href's der img's umschreiben so dass das über den media manager läuft.

eigentlich würd auch ein str_replace schon tun. einfach nach `/media/` suchen und ersetzen mit `index.php?rex_media_type=ImgTypeName&rex_media_file=`

**Comment by RexDude** [comment]
Output manipulieren ist auch in der readme beschrieben.

**Comment by RexDude** [comment]
und noch ne idee: den precompressor könnt man auch verwenden dann haben sie immer ne maximal größe bei upload zumindest schon mal.

**Comment by georgkaser** [comment]
Ja, die Abstände und Rahmen würd ich auch wegmachen. Kann man überhaupt die floating Inline Styles gegen Klassen austauschen? Dürfte ja kein Problem sein, oder?

Klar, das mit den str_replace hab ich mir auch schon überlegt. Cool wärs halt, wenn man da gar nichts machen muss. Ist aber echt nicht dringend...

Danke dir!

**Comment by RexDude** [comment]
Zuerstmal ziehst du dir am besten die neuste Version. Und dann alte deinstall und neue installieren.
Im lite und standard profil sind die Rahmen etc. rausgefiltert (kann man aber selber ändern).
in der Readme gibts ne Rubrik "Bilder als Media Manager Urls umschreiben" extra für deine UseCase (also Workaround).
Floats kann man nicht so einfach entfernen leider.
Was aber geht: Image Plugin hernehmen, umschreiben ohne floats etc, umbennen und in dein project addon schmeissen. Da bist du also frei dir dass so einzurichten wie du magst :)
Und nund viel Spaß damit. Jetzt ist alles drin was wichtig ist :)

**Comment by georgkaser** [comment]
Ja, dann mach ich das so :) Danke und schönen Abend noch.

**Comment by fietstouring** [comment]
Bilder mit inline float Stilen style ich einfach über `.ckeditor img[float="left"]`, so gehts auch ohne Klasse...

**Comment by RexDude** [comment]
cool. und ich wollt noch vorschlagen per str_replace den inline style mit klasse zu ersetzen aber dass ist natürlich super elegant :)

**Comment by fietstouring** [comment]
muss natürlich img[style*="left"] heißen...

**Comment by RexDude** [comment]
das erstere sah aufjedefall hübscher aus :))
hab das codebeispiel in der readme ergänzt...

**Comment by georgkaser** [comment]
Klasse, danke. Hab das sogar schon mal benutzt - jedoch irgendwie wieder vergessen :D

**Comment by RexDude** [comment]
Ich danke euch. Ist jetzt richtig rund geworden :)
Werde noch dass Preview Fenster ganz killen. Bitte schreien wenns jemand vermissen würd ;)
