### ISSUE TITLE
Initialisierungsdauer vom Editor 

### ISSUE THREAD

**Issue by joachimdoerr** [RexDude/ckeditor#33]
Generell benötigt der Editor sehr viel Zeit bis er initialisiert. Das liegt wohl daran, dass 2mal die Config geladen wird.

**Comment by RexDude** [comment]
welche config?

**Comment by RexDude** [comment]
und wo siehst du das mit dem 2 maligen laden?

**Comment by joachimdoerr** [comment]
Einmal wird die volle Config und einmal die Config geladen die man für die Textarea definiert hat.

**Comment by RexDude** [comment]
Joachim ich brauche hier mehr infos. wo siehst du dass? und warum denkst du dass es an der config liegt. ist ja eigentllich nur ein js array bzw. objekt.

und wie kann man dass verbessern wäre dann die nächste frage an dich ;)

**Comment by RexDude** [comment]
@ynamite

> Zum anderen:
Lösche den code aus deinem redaxo.js und lade den Modul-Input mit einer textarea mit der Klasse ckeditor. Der ckeditor wird geladen ...

ja klar aber wieso schliesst du drauss dass er dann dopplet geladen wird. normla ist der ck n icht doof und initialisiert sich nicht zweit mal. ich brauch beweise bitte ;)

**Comment by RexDude** [comment]
@ynamite

übrigens wenn ich den aufruf hier entferne initialisiert sich gar nix mehr(was mich selber wundert).  
https://github.com/RexDude/ckeditor/blob/master/assets/redaxo.js#L95

**Comment by ynamite** [comment]
Kann ich dir nicht genau sagen. Bei mir wird der Editor geladen wenn redaxo.js ganz leer ist. Wenn ich die Klasse `ckeditor` rausnehme und den Editor ausschliesslich manuel lade, lädt er schneller.

**Comment by RexDude** [comment]
ok ich werd in auf .rex-ckeditor initilaisieren lassen. @ynamite ok?
