### ISSUE TITLE
Function profileExists 

### ISSUE THREAD

**Issue by rkemmere** [RexDude/ckeditor#35]
Hallo Rexdude, 

kann der CKeditor um die Funktion profileExists erweitert werden? 
Dann kann man diese ebenfalls in den Textmodulen abfragen wie bereits bei Redaktor und Markitup.

` public static function profileExists ($name) {
             $sql = rex_sql::factory();
             $profile = $sql->setQuery("SELECT name FROM ".rex::getTablePrefix()."ckeditor_profiles WHERE name = ".$sql->escape($name)."")->getArray();
             unset($sql);                    
             if (!empty($profile)) {
                    return true;
             } else {
                    return false;
             }
       }
`

Danke und viele Grüße
Ronny

**Comment by RexDude** [comment]
Super Danke Ronny! :)

**Comment by rkemmere** [comment]
Gerne…

 

 

Von: RexDude 2.0 [mailto:notifications@github.com] 
Gesendet: Dienstag, 22. August 2017 21:31
An: RexDude/ckeditor <ckeditor@noreply.github.com>
Cc: rkemmere <rkemmereit@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [RexDude/ckeditor] Function profileExists (#35)

 

Super Danke Ronny! :)
