### ISSUE TITLE
Gibt es eine addprofile() - Funktion ?

### ISSUE THREAD

**Issue by skerbis** [RexDude/ckeditor#36]
wenn ja. Wie sähe der Code aus?

**Comment by RexDude** [comment]
nö gibts nicht. macht man ja alles übers backend. würde dass nur einbauen wenns einen konkreten use case gibt. aussehen wäre so: methodendenparamater wären die die die man beim profilanlegen abfrägt. methodenlogik wäre die sachen in die db zu seichern per INSERT und die js cache datei per `rex_ckeditor::writeProfileJSFile();` neu generieren zu lassen.

**Comment by skerbis** [comment]
Im Glossar-Addon, prüfen wir aktuell welche Editoren zur Verfügung stehen bei der Installation und legen automatisch passende Profile an, so dass der Nutzer nur noch die CSS-Class wählen muss um den gewünschten Editor zu erhalten. Das ist ganz praktisch denke ich. 

https://github.com/FriendsOfREDAXO/multiglossar/blob/cf99c45d1ce034037f0370f9e6047002b6c415cb/install.php#L22

**Comment by RexDude** [comment]
ja wenn das so ist kannst gerne die methode beitragen wenn du magst...

**Comment by skerbis** [comment]
https://github.com/RexDude/ckeditor/pull/38

**Comment by RexDude** [comment]
Super gemacht! Danke!

**Comment by skerbis** [comment]
Bitte schön
