### ISSUE TITLE
MBlock-Funktionalität

### ISSUE THREAD

**Issue by dpf-dd** [RexDude/ckeditor#37]
Hallo RexDude,

wie ich soeben gemerkt und hier jetzt auch gelesen habe: Es gibt keine MBlock-Kompatibilität :(
Ist da von deiner Seite etwas geplant oder müsste man sich mit diesem Enhancement eher an den MBlock-Autor wenden?

Die Workarounds finde ich nicht ansprechend, ein Redaxo-CKE mit MBlock-Funktionalität wäre der absolute Burner und für mich eine unschlagbare Kombination :)

Danke für eine kurze Antwort und viele Grüße
dpf-dd

**Comment by RexDude** [comment]
Hi :) Ja dass haben wir alle irgendwie nicht hinbekommen obwohl der Wille da war :) Siehe diverse Issues und ein PR (bereits geschlossene) hier in der Repo. Du (oder jemand anders) kannst dich der Sache gerne annehmen. Aber es wäre nett wenn was gut getestetet dann hier ankommt :)

**Comment by mhut47** [comment]
oh! Schade

**Comment by RexDude** [comment]
@mhut47 wie ich sehe gibts ein ckeditor5 addon mit mblock support bei FriendsOfRedaxo. Versuch es doch mal damit.
