### ISSUE TITLE
Styles on Links and UL 

### ISSUE THREAD

**Issue by rkemmere** [RexDude/ckeditor#40]
Hallo Rexdude,

wir haben in der aktuellen Version folgenden Fehler gefunden:
Es können keine Styles auf Links und UL mehr gesetzt werden.

```
CKEDITOR.stylesSet.add('default', [
        { name: 'Absatz', element: 'p', attributes: { 'class': 'msg info' } },
        { name: 'Liste mit Haken', element: 'ul', attributes: { 'class': 'tick' } },
        { name: 'Logo', element: 'img', attributes: { 'class': 'logo' } },
        { name: 'externer Link', element: 'a', attributes: { 'rel': 'external' } },
        { name: 'Tabelle alternativ', element: 'table', attributes: { 'class': 'alt' } }
        // no comma after last entry!!!
    ]);
```

Liste mit Haken und externer Link ist nicht möglich zu setzen. Wir haben auch mal versucht styles anstelle von class zu setzen. Diese sind auch für Links nicht möglich zu setzen.

Viele Grüße
Ronny

**Comment by RexDude** [comment]
Hi Ronny,
probier mal den "amtlichen" Weg so wie in der Readme beschrieben unter "Custom Styles hinzufügen". Wo bzw. wie du `CKEDITOR.stylesSet.add` benutzt ist mir eh rätselhatf weil im Profil (= JS Config Objekt) hat der Aufruf einer JS Funktion nix verloren.

**Comment by RexDude** [comment]
poste doch mal dein gesmates config objekt bitte, evtl. kann ich was entdecken...

**Comment by rkemmere** [comment]
Bitteschön. Ich bekomme ja zumindest Stil aktiv gezeigt bei einem Link. Aber das Dropdown ist leer bei dem a. Teste es doch mal bei Dir mit einem Standardmodul?!

```
{
    height: 400,
    fillEmptyBlocks: false,
    forcePasteAsPlainText: true,
    entities: false,
    linkShowTargetTab: true,
    format_tags: 'p;h1;h2;h3;pre',
    removePlugins: '',
    extraPlugins: 'rex_help',
    removeDialogTabs: '',
    disallowedContent: '',
    toolbar: [
        ['Cut', 'Copy', '-', 'Undo', 'Redo'],
        ['Source', '-'],
        '/',
        ['Format', 'Styles', '-' , 'Bold', 'Italic', 'Underline', 'Subscript', 'Superscript', '-', 'RemoveFormat', '-', 'Outdent', 'Indent'],
        ['BulletedList', '-', 'Table'],
        ['Link', 'Unlink','-','Button']
       
        // no comma after last entry!!!
    ],
   stylesSet: [
        { name: 'Button', element: 'a', attributes: { 'class': 'btn' } }
        // no comma after last entry!!!
    ]
    // no comma after last entry!!!
}
```

**Comment by RexDude** [comment]
ok scheint ein bug im ck zu sein seit 4.7.2 der dann in der 4.8.0 wieder gefixt wurde. bitte mal die aktuelle github version ziehen, diese dann bei dir im addon folder ersetzen und dass addon reinstallieren. gehts dann wieder?

**Comment by rkemmere** [comment]
Joop geht wieder. Danke für den schnellen fix und die Hilfe. Habe nur schnell die Vendor ausgetauscht und update dann später auf die Version über den Installer.

**Comment by RexDude** [comment]
Ja ich mach mal ne 4.8.0beta1 fertig damit du auch was zum "über den Installer ziehen" hast ;)

**Comment by RexDude** [comment]
ok ist im installer. bitte von da ziehen (zum testen weil ich upload probs hatte)...
