### ISSUE TITLE
interne Links und Medienpool-Links funktionieren im IE und im MS Edge nicht

### ISSUE THREAD

**Issue by WolfgangBusch** [RexDude/ckeditor#41]
Hallo,
 das Setzen interner Links bzw. Medienpool Links im CKEdotor (Redaxo 5.3, CKEditor Standard Vers. 4.8.0) funktioniert, abhängig vom gewählten Browser, teilweise nur eingeschränkt:
 Internet Explorer (11.125.16299.0):
- interner Link: Javascript hängt, liefert keinen Link (!)
- Medienpool Link: Javascript hängt, liefert keinen Link (!)
 Microsoft Edge (41.16299.15.0):
 - interner Link: wird geliefert (redaxo://ID)
- Medienpool Link: Javascript hängt, liefert keinen Link (!)
 Firefox (Quantum 57.0.2):
 - interner Link: wird geliefert (redaxo://ID)
 - Medienpool Link: wird geliefert (/media/bild.jpg)
 Lässt sich die Adaption des CKEditors besser anpassen?

**Comment by RexDude** [comment]
Hi und danke für den ausführlichen Fehlerbericht. Ich kann dass Verhalten im IE11 bestätigen. Leider kommt aber keinerlei Fehlermeldung über die JS Konsole rein. Kannst du vielleicht mal bei dir schauen? Per F12 dann Reiter "Konsole" im IE.

**Comment by WolfgangBusch** [comment]
Hallo, ich bekomme in beiden Fällen eine Javascript-Fehlermeldung:
interner Link:
in `function insertLink(link,name)` tritt der Fehler auf in Statement
`window.opener.document.getElementById("").value = linkid;`
_Die Eigenschaft "value" eines undefinierten oder Nullverweises kann nicht festgelegt werden._
Medienpool-Link:
in `function selectMedia(filename, alt)` tritt der Fehler auf in Statement
`opener.document.getElementById(opener_input_field).value = filename;`
_Die Eigenschaft "value" eines undefinierten oder Nullverweises kann nicht festgelegt werden._

**Comment by RexDude** [comment]
Danke dir! Siehe vorerst: https://github.com/redaxo/redaxo/issues/1509

**Comment by WolfgangBusch** [comment]
Ich habe wegen meiner Vorliebe für Microsoft-Browser nach einer Alternative für CKEditor gesucht. Dabei bin ich auf Redaktor gestoßen. Leider **hat Redaktor dieselben Probleme** wie der CKEditor mit dem Setzen interner Links bzw. Medienpool Links im IE und im MS Edge!
Dann habe ich den TinyMCE 4 versucht und war damit erfolgreich. Außerdem gefällt mir dieser HTML-Editor auch in seinem Menüaufbau besser als die anderen beiden. Ich habe also im Moment gute Gründe, auf CKEditor und Redaktor zu verzichten.

**Comment by RexDude** [comment]
Sollte dann ab CKEditor Addon 4.8.0-beta1 gefixt sein.

**Comment by WolfgangBusch** [comment]
Ich habe gerade die neueste CKEditor-Version 4.9.0 installiert. Alles unverändert. Keinerlei Verbesserung im Falle des IE.

**Comment by WolfgangBusch** [comment]
nicht 4.9.0 sondern 4.9.2

**Comment by RexDude** [comment]
Liegt nicht am CK. Ist anscheiend ein Core Problem. Siehe: https://github.com/redaxo/redaxo/issues/1509
Evtl. kannst du es fixen? Da scheint sich nämlich keiner drum kümmern zu wollen.
