### ISSUE TITLE
CKE - Redactor 2 im Newsmanager

### ISSUE THREAD

**Issue by spiritandsoul** [RexDude/ckeditor#42]
Hey Rudi,
ich glaub ich hab im CKE einen kleinen Bug gefunden. Ich nutze den CKE für meinen Seiten, weißt ja. Nur beim Newsmanager geht bis jetzt nur der Redactor 2.

Wenn ich einen Artikel neu anlegen oder bearbeiten will legen sich Teile des CKE über redactor 2 wenn man verlinken kommt so ein Quellcode bei rum:

`<a data-cke-saved-href="#!" href="#!">Testlink</a>`

Damit du mal ein Bild bekommst, siehe Screenshot:

![2018-01-05 1](https://user-images.githubusercontent.com/34594030/34601460-622fc422-f1fc-11e7-8fac-0747b4c4fbf4.png)

Sobald ich den Text bearbeiten will zeigt sich das:

![2018-01-05 2](https://user-images.githubusercontent.com/34594030/34601486-7e132904-f1fc-11e7-8ff5-48191a57cbff.png)

LG Christian

**Comment by webregie** [comment]
Z.234 in der pages/main.php 
$field = $form->addTextAreaField('richtext', null, array('class'=>'tinyMCEEditor') );
oder eben die Klasse ckeditor

**Comment by spiritandsoul** [comment]
Danke Ralf. Läuft unabhängig von redactor 2 :-)

**Comment by webregie** [comment]
Das passt wohl zu dem Problem im anderen Issue, dass Bilder zusammen mit dem Text abgefragt werden und nicht separat in der Detailansicht. 
Ich hoffe hier auf eine Idee zur Nachbesserung...

**Comment by RexDude** [comment]
Das Problem ist hier dass der Redactor ein contenteditable Attribut zur Textarea hinzufügt und damit die auto. init vom CK triggert. Kann man auf CK Seite abschalten aber weiss net ob dann bei manchen die Editoren nicht mehr initialisieren. Deshalb am besten in dem jeweiligen Addon ändern.

**Comment by spiritandsoul** [comment]
Rudis Lösung wenn Du CKE und Newsmanager nutzt. Gilt für den aktuellen CK.

```
<?php
if (rex::isBackend() && rex_be_controller::getCurrentPagePart(1) != 'newsletter') {
  if (rex::isBackend() && rex::getUser() instanceof rex_user) {
    if ($this->getConfig('patches_applied') == 0) {
      // apply patches
      rex_ckeditor::applyPatches();

      $this->setConfig('patches_applied', 1);
    }

    if (!file_exists(rex_ckeditor::getAbsoluteProfileJSFile())) {
      rex_ckeditor::writeProfileJSFile();
    }
  
    rex_view::addJsFile($this->getAssetsUrl('vendor/ckeditor.js'));
    rex_view::addJsFile(rex_ckeditor::getRelativeProfileJSFile());
    rex_view::addJsFile($this->getAssetsUrl('redaxo.js'));
    rex_view::addCssFile($this->getAssetsUrl('backend.css'));

    rex_extension::register('CACHE_DELETED', function () {
      rex_ckeditor::writeProfileJSFile();
    });

    rex_extension::register('BACKUP_AFTER_DB_IMPORT', function () {
      rex_ckeditor::writeProfileJSFile();
    });
  }
```
