### ISSUE TITLE
Iframes

### ISSUE THREAD

**Issue by fietstouring** [RexDude/ckeditor#44]
Hi Rudi,
Du weißt vielleicht wie man in den CK-Editor iFrames tun kann?
Grundsätzlich schmeißt er solchen Code einfach raus. Gibt´s nen Override?

**Comment by skerbis** [comment]
Warum sollte man im Editor ein iFrame einsetzen dürfen? Ist da nicht ein eigener Block dafür viel sinnvoller?

**Comment by RexDude** [comment]
Würde da skerbis zustimmen.
Sonst gibts glaub ich ein Iframe Plugin. Am besten mal Google fragen...
